@startuml useVarianr2
left to right direction
actor "Бухгалтер" as B
actor "Администратор Системы" as AS
actor "Сотрудник" as S

rectangle "Финансы и Документы" {
  B --> (Вести учет финансов)
  B --> (Подготовить отчеты)
  B --> (Расчет зарплат)
  B --> (Управление налогами)
  
  AS --> (Управление доступом)
  AS --> (Настройка системы)
  
  S --> (Доступ к документам)
  S --> (Загрузка документов)
}

@enduml
