@startuml useVariant1
left to right direction
actor "Руководитель Проектов" as RP
actor "Кладовщик" as K
actor "Менеджер" as M

rectangle "Управление Проектами" {
  RP --> (Создать проект)
  RP --> (Назначить задачи)
  RP --> (Отслеживать прогресс)
  RP --> (Редактировать проект)
  
  K --> (Управление складом)
  K --> (Отслеживать запасы)
  
  M --> (Просмотреть проекты)
  M --> (Обновить статус проекта)
}

@enduml
